// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioEncoder(Int) from Int to Int {
	public static inline function create(codec:String, sampleRate:haxe.Int64, channels:haxe.Int64, bitrate:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):AudioEncoder return AudioEncoderNative.create(codec, sampleRate, channels, bitrate, maxItems, maxBytes);
	public inline function tryEncode(value:AudioData):Bool return AudioEncoderNative.tryEncode(this, value);
	public inline function poll():StreamReadStatus return AudioEncoderNative.poll(this);
	public inline function read():EncodedAudioChunk return AudioEncoderNative.read(this);
	public inline function finish():Void AudioEncoderNative.finish(this);
	public inline function close():Void AudioEncoderNative.close(this);
	public inline function getConfiguration():CodecConfiguration return AudioEncoderNative.getConfiguration(this);
}

private extern class AudioEncoderNative {
	@:hlNative("xavi", "audio_encoder_create")
	public static function create(codec:String, sampleRate:haxe.Int64, channels:haxe.Int64, bitrate:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):AudioEncoder;
	@:hlNative("xavi", "audio_encoder_try_encode")
	public static function tryEncode(self:Int, value:AudioData):Bool;
	@:hlNative("xavi", "audio_encoder_poll")
	public static function poll(self:Int):StreamReadStatus;
	@:hlNative("xavi", "audio_encoder_read")
	public static function read(self:Int):EncodedAudioChunk;
	@:hlNative("xavi", "audio_encoder_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "audio_encoder_close")
	public static function close(self:Int):Void;
	@:hlNative("xavi", "audio_encoder_get_configuration")
	public static function getConfiguration(self:Int):CodecConfiguration;
}
