// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioDataInit(hl.Abstract<"xavi_AudioDataInit">) {
	public inline function new(format:AudioSampleFormat, sampleRate:Float, numberOfFrames:haxe.Int64, numberOfChannels:haxe.Int64, timestamp:haxe.Int64, data:haxe.io.Bytes) this = AudioDataInitNative.create(format, sampleRate, numberOfFrames, numberOfChannels, timestamp, data);
}

private extern class AudioDataInitNative {
	@:hlNative("xavi", "audio_data_init_new")
	public static function create(format:AudioSampleFormat, sampleRate:Float, numberOfFrames:haxe.Int64, numberOfChannels:haxe.Int64, timestamp:haxe.Int64, data:haxe.io.Bytes):hl.Abstract<"xavi_AudioDataInit">;
}
