// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract AudioSampleFormat(Int) from Int to Int {
	var U8 = 0;
	var S16 = 1;
	var S32 = 2;
	var F32 = 3;
	var U8Planar = 4;
	var S16Planar = 5;
	var S32Planar = 6;
	var F32Planar = 7;
}
