// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioData(Int) from Int to Int {
	public static inline function create(init:AudioDataInit):AudioData return AudioDataNative.create(init);
	public inline function format():AudioSampleFormat return AudioDataNative.format(this);
	public inline function sampleRate():Float return AudioDataNative.sampleRate(this);
	public inline function numberOfFrames():haxe.Int64 return AudioDataNative.numberOfFrames(this);
	public inline function numberOfChannels():haxe.Int64 return AudioDataNative.numberOfChannels(this);
	public inline function timestamp():haxe.Int64 return AudioDataNative.timestamp(this);
	public inline function duration():haxe.Int64 return AudioDataNative.duration(this);
	public inline function allocationSize(options:AudioDataCopyToOptions):haxe.Int64 return AudioDataNative.allocationSize(this, options);
	public inline function copyTo(destination:haxe.io.Bytes, options:AudioDataCopyToOptions):Void AudioDataNative.copyTo(this, destination, options);
	public inline function clone():AudioData return AudioDataNative.clone(this);
	public inline function close():Void AudioDataNative.close(this);
}

private extern class AudioDataNative {
	@:hlNative("xavi", "audio_data_create")
	public static function create(init:AudioDataInit):AudioData;
	@:hlNative("xavi", "audio_data_format")
	public static function format(self:Int):AudioSampleFormat;
	@:hlNative("xavi", "audio_data_sample_rate")
	public static function sampleRate(self:Int):Float;
	@:hlNative("xavi", "audio_data_number_of_frames")
	public static function numberOfFrames(self:Int):haxe.Int64;
	@:hlNative("xavi", "audio_data_number_of_channels")
	public static function numberOfChannels(self:Int):haxe.Int64;
	@:hlNative("xavi", "audio_data_timestamp")
	public static function timestamp(self:Int):haxe.Int64;
	@:hlNative("xavi", "audio_data_duration")
	public static function duration(self:Int):haxe.Int64;
	@:hlNative("xavi", "audio_data_allocation_size")
	public static function allocationSize(self:Int, options:AudioDataCopyToOptions):haxe.Int64;
	@:hlNative("xavi", "audio_data_copy_to")
	public static function copyTo(self:Int, destination:haxe.io.Bytes, options:AudioDataCopyToOptions):Void;
	@:hlNative("xavi", "audio_data_clone")
	public static function clone(self:Int):AudioData;
	@:hlNative("xavi", "audio_data_close")
	public static function close(self:Int):Void;
}
