// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioDecoder(Int) from Int to Int {
	public static inline function create(maxItems:Int, maxBytes:haxe.Int64, configuration:CodecConfiguration):AudioDecoder return AudioDecoderNative.create(maxItems, maxBytes, configuration);
	public inline function tryDecode(value:EncodedAudioChunk):Bool return AudioDecoderNative.tryDecode(this, value);
	public inline function poll():StreamReadStatus return AudioDecoderNative.poll(this);
	public inline function read():AudioData return AudioDecoderNative.read(this);
	public inline function finish():Void AudioDecoderNative.finish(this);
	public inline function close():Void AudioDecoderNative.close(this);
}

private extern class AudioDecoderNative {
	@:hlNative("xavi", "audio_decoder_create")
	public static function create(maxItems:Int, maxBytes:haxe.Int64, configuration:CodecConfiguration):AudioDecoder;
	@:hlNative("xavi", "audio_decoder_try_decode")
	public static function tryDecode(self:Int, value:EncodedAudioChunk):Bool;
	@:hlNative("xavi", "audio_decoder_poll")
	public static function poll(self:Int):StreamReadStatus;
	@:hlNative("xavi", "audio_decoder_read")
	public static function read(self:Int):AudioData;
	@:hlNative("xavi", "audio_decoder_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "audio_decoder_close")
	public static function close(self:Int):Void;
}
