// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioEqualizer(Int) from Int to Int {
	public static inline function create(bands:Int):AudioEqualizer return AudioEqualizerNative.create(bands);
	public inline function bandCount():Int return AudioEqualizerNative.bandCount(this);
	public inline function setBand(index:Int, frequency:Float, gainDb:Float, q:Float):Void AudioEqualizerNative.setBand(this, index, frequency, gainDb, q);
	public inline function disableBand(index:Int):Void AudioEqualizerNative.disableBand(this, index);
	public inline function bandFrequency(index:Int):Float return AudioEqualizerNative.bandFrequency(this, index);
	public inline function bandGain(index:Int):Float return AudioEqualizerNative.bandGain(this, index);
	public inline function bandQ(index:Int):Float return AudioEqualizerNative.bandQ(this, index);
	public inline function bandEnabled(index:Int):Bool return AudioEqualizerNative.bandEnabled(this, index);
	public inline function setPreamp(gainDb:Float):Void AudioEqualizerNative.setPreamp(this, gainDb);
	public inline function preamp():Float return AudioEqualizerNative.preamp(this);
	public inline function setBypass(bypass:Bool):Void AudioEqualizerNative.setBypass(this, bypass);
	public inline function bypassed():Bool return AudioEqualizerNative.bypassed(this);
	public inline function process(data:AudioData):AudioData return AudioEqualizerNative.process(this, data);
	public inline function reset():Void AudioEqualizerNative.reset(this);
	public inline function close():Void AudioEqualizerNative.close(this);
}

private extern class AudioEqualizerNative {
	@:hlNative("xavi", "audio_equalizer_create")
	public static function create(bands:Int):AudioEqualizer;
	@:hlNative("xavi", "audio_equalizer_band_count")
	public static function bandCount(self:Int):Int;
	@:hlNative("xavi", "audio_equalizer_set_band")
	public static function setBand(self:Int, index:Int, frequency:Float, gainDb:Float, q:Float):Void;
	@:hlNative("xavi", "audio_equalizer_disable_band")
	public static function disableBand(self:Int, index:Int):Void;
	@:hlNative("xavi", "audio_equalizer_band_frequency")
	public static function bandFrequency(self:Int, index:Int):Float;
	@:hlNative("xavi", "audio_equalizer_band_gain")
	public static function bandGain(self:Int, index:Int):Float;
	@:hlNative("xavi", "audio_equalizer_band_q")
	public static function bandQ(self:Int, index:Int):Float;
	@:hlNative("xavi", "audio_equalizer_band_enabled")
	public static function bandEnabled(self:Int, index:Int):Bool;
	@:hlNative("xavi", "audio_equalizer_set_preamp")
	public static function setPreamp(self:Int, gainDb:Float):Void;
	@:hlNative("xavi", "audio_equalizer_preamp")
	public static function preamp(self:Int):Float;
	@:hlNative("xavi", "audio_equalizer_set_bypass")
	public static function setBypass(self:Int, bypass:Bool):Void;
	@:hlNative("xavi", "audio_equalizer_bypassed")
	public static function bypassed(self:Int):Bool;
	@:hlNative("xavi", "audio_equalizer_process")
	public static function process(self:Int, data:AudioData):AudioData;
	@:hlNative("xavi", "audio_equalizer_reset")
	public static function reset(self:Int):Void;
	@:hlNative("xavi", "audio_equalizer_close")
	public static function close(self:Int):Void;
}
