// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract AudioDataCopyToOptions(hl.Abstract<"xavi_AudioDataCopyToOptions">) {
	public inline function new(planeIndex:haxe.Int64) this = AudioDataCopyToOptionsNative.create(planeIndex);
	public inline function frameOffset(value:haxe.Int64):Void AudioDataCopyToOptionsNative.frameOffset(this, value);
	public inline function frameCount(value:haxe.Int64):Void AudioDataCopyToOptionsNative.frameCount(this, value);
	public inline function format(value:AudioSampleFormat):Void AudioDataCopyToOptionsNative.format(this, value);
}

private extern class AudioDataCopyToOptionsNative {
	@:hlNative("xavi", "audio_data_copy_to_options_new")
	public static function create(planeIndex:haxe.Int64):hl.Abstract<"xavi_AudioDataCopyToOptions">;
	@:hlNative("xavi", "audio_data_copy_to_options_frame_offset")
	public static function frameOffset(self:hl.Abstract<"xavi_AudioDataCopyToOptions">, value:haxe.Int64):Void;
	@:hlNative("xavi", "audio_data_copy_to_options_frame_count")
	public static function frameCount(self:hl.Abstract<"xavi_AudioDataCopyToOptions">, value:haxe.Int64):Void;
	@:hlNative("xavi", "audio_data_copy_to_options_format")
	public static function format(self:hl.Abstract<"xavi_AudioDataCopyToOptions">, value:AudioSampleFormat):Void;
}
