// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract CodecConfiguration(Int) from Int to Int {
	public static inline function audio(codec:String, sampleRate:haxe.Int64, channels:haxe.Int64, description:haxe.io.Bytes):CodecConfiguration return CodecConfigurationNative.audio(codec, sampleRate, channels, description);
	public static inline function video(codec:String, width:haxe.Int64, height:haxe.Int64, description:haxe.io.Bytes):CodecConfiguration return CodecConfigurationNative.video(codec, width, height, description);
	public inline function codec():String { var value = CodecConfigurationNative.codec(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function sampleRate():haxe.Int64 return CodecConfigurationNative.sampleRate(this);
	public inline function numberOfChannels():haxe.Int64 return CodecConfigurationNative.numberOfChannels(this);
	public inline function codedWidth():haxe.Int64 return CodecConfigurationNative.codedWidth(this);
	public inline function codedHeight():haxe.Int64 return CodecConfigurationNative.codedHeight(this);
	public inline function descriptionSize():haxe.Int64 return CodecConfigurationNative.descriptionSize(this);
	public inline function copyDescription(destination:haxe.io.Bytes):Void CodecConfigurationNative.copyDescription(this, destination);
	public inline function close():Void CodecConfigurationNative.close(this);
}

private extern class CodecConfigurationNative {
	@:hlNative("xavi", "codec_configuration_audio")
	public static function audio(codec:String, sampleRate:haxe.Int64, channels:haxe.Int64, description:haxe.io.Bytes):CodecConfiguration;
	@:hlNative("xavi", "codec_configuration_video")
	public static function video(codec:String, width:haxe.Int64, height:haxe.Int64, description:haxe.io.Bytes):CodecConfiguration;
	@:hlNative("xavi", "codec_configuration_codec")
	public static function codec(self:Int):hl.Bytes;
	@:hlNative("xavi", "codec_configuration_sample_rate")
	public static function sampleRate(self:Int):haxe.Int64;
	@:hlNative("xavi", "codec_configuration_number_of_channels")
	public static function numberOfChannels(self:Int):haxe.Int64;
	@:hlNative("xavi", "codec_configuration_coded_width")
	public static function codedWidth(self:Int):haxe.Int64;
	@:hlNative("xavi", "codec_configuration_coded_height")
	public static function codedHeight(self:Int):haxe.Int64;
	@:hlNative("xavi", "codec_configuration_description_size")
	public static function descriptionSize(self:Int):haxe.Int64;
	@:hlNative("xavi", "codec_configuration_copy_description")
	public static function copyDescription(self:Int, destination:haxe.io.Bytes):Void;
	@:hlNative("xavi", "codec_configuration_close")
	public static function close(self:Int):Void;
}
