// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract DOMRectInit(hl.Abstract<"xavi_DOMRectInit">) {
	public inline function new() this = DOMRectInitNative.create();
	public inline function x(value:Float):Void DOMRectInitNative.x(this, value);
	public inline function y(value:Float):Void DOMRectInitNative.y(this, value);
	public inline function width(value:Float):Void DOMRectInitNative.width(this, value);
	public inline function height(value:Float):Void DOMRectInitNative.height(this, value);
}

private extern class DOMRectInitNative {
	@:hlNative("xavi", "d_o_m_rect_init_new")
	public static function create():hl.Abstract<"xavi_DOMRectInit">;
	@:hlNative("xavi", "d_o_m_rect_init_x")
	public static function x(self:hl.Abstract<"xavi_DOMRectInit">, value:Float):Void;
	@:hlNative("xavi", "d_o_m_rect_init_y")
	public static function y(self:hl.Abstract<"xavi_DOMRectInit">, value:Float):Void;
	@:hlNative("xavi", "d_o_m_rect_init_width")
	public static function width(self:hl.Abstract<"xavi_DOMRectInit">, value:Float):Void;
	@:hlNative("xavi", "d_o_m_rect_init_height")
	public static function height(self:hl.Abstract<"xavi_DOMRectInit">, value:Float):Void;
}
