// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract EncodedAudioChunkInit(hl.Abstract<"xavi_EncodedAudioChunkInit">) {
	public inline function new(type:EncodedChunkType, timestamp:haxe.Int64, data:haxe.io.Bytes) this = EncodedAudioChunkInitNative.create(type, timestamp, data);
	public inline function duration(value:haxe.Int64):Void EncodedAudioChunkInitNative.duration(this, value);
}

private extern class EncodedAudioChunkInitNative {
	@:hlNative("xavi", "encoded_audio_chunk_init_new")
	public static function create(type:EncodedChunkType, timestamp:haxe.Int64, data:haxe.io.Bytes):hl.Abstract<"xavi_EncodedAudioChunkInit">;
	@:hlNative("xavi", "encoded_audio_chunk_init_duration")
	public static function duration(self:hl.Abstract<"xavi_EncodedAudioChunkInit">, value:haxe.Int64):Void;
}
