// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract EncodedAudioChunk(Int) from Int to Int {
	public static inline function create(init:EncodedAudioChunkInit):EncodedAudioChunk return EncodedAudioChunkNative.create(init);
	public inline function kind():EncodedChunkType return EncodedAudioChunkNative.kind(this);
	public inline function timestamp():haxe.Int64 return EncodedAudioChunkNative.timestamp(this);
	static inline function readOptionalDuration(index:Int):OptionalDuration {
		return switch (index) {
			case 1: OptionalDuration.Value(EncodedAudioChunkNative.optionalDurationValueMicroseconds());
			default: OptionalDuration.Unknown;
		};
	}
	public inline function duration():OptionalDuration {
		return readOptionalDuration(EncodedAudioChunkNative.durationVariant(this));
	}
	public inline function byteLength():haxe.Int64 return EncodedAudioChunkNative.byteLength(this);
	public inline function copyTo(destination:haxe.io.Bytes):Void EncodedAudioChunkNative.copyTo(this, destination);
	public inline function close():Void EncodedAudioChunkNative.close(this);
}

private extern class EncodedAudioChunkNative {
	@:hlNative("xavi", "encoded_audio_chunk_create")
	public static function create(init:EncodedAudioChunkInit):EncodedAudioChunk;
	@:hlNative("xavi", "encoded_audio_chunk_kind")
	public static function kind(self:Int):EncodedChunkType;
	@:hlNative("xavi", "encoded_audio_chunk_timestamp")
	public static function timestamp(self:Int):haxe.Int64;
	@:hlNative("xavi", "encoded_audio_chunk_duration_variant")
	public static function durationVariant(self:Int):Int;
	@:hlNative("xavi", "encoded_audio_chunk_optional_duration_value_microseconds")
	public static function optionalDurationValueMicroseconds():haxe.Int64;
	@:hlNative("xavi", "encoded_audio_chunk_byte_length")
	public static function byteLength(self:Int):haxe.Int64;
	@:hlNative("xavi", "encoded_audio_chunk_copy_to")
	public static function copyTo(self:Int, destination:haxe.io.Bytes):Void;
	@:hlNative("xavi", "encoded_audio_chunk_close")
	public static function close(self:Int):Void;
}
