// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract EncodedVideoChunk(Int) from Int to Int {
	public static inline function create(init:EncodedVideoChunkInit):EncodedVideoChunk return EncodedVideoChunkNative.create(init);
	public inline function kind():EncodedChunkType return EncodedVideoChunkNative.kind(this);
	public inline function timestamp():haxe.Int64 return EncodedVideoChunkNative.timestamp(this);
	static inline function readOptionalDuration(index:Int):OptionalDuration {
		return switch (index) {
			case 1: OptionalDuration.Value(EncodedVideoChunkNative.optionalDurationValueMicroseconds());
			default: OptionalDuration.Unknown;
		};
	}
	public inline function duration():OptionalDuration {
		return readOptionalDuration(EncodedVideoChunkNative.durationVariant(this));
	}
	public inline function byteLength():haxe.Int64 return EncodedVideoChunkNative.byteLength(this);
	public inline function copyTo(destination:haxe.io.Bytes):Void EncodedVideoChunkNative.copyTo(this, destination);
	public inline function close():Void EncodedVideoChunkNative.close(this);
}

private extern class EncodedVideoChunkNative {
	@:hlNative("xavi", "encoded_video_chunk_create")
	public static function create(init:EncodedVideoChunkInit):EncodedVideoChunk;
	@:hlNative("xavi", "encoded_video_chunk_kind")
	public static function kind(self:Int):EncodedChunkType;
	@:hlNative("xavi", "encoded_video_chunk_timestamp")
	public static function timestamp(self:Int):haxe.Int64;
	@:hlNative("xavi", "encoded_video_chunk_duration_variant")
	public static function durationVariant(self:Int):Int;
	@:hlNative("xavi", "encoded_video_chunk_optional_duration_value_microseconds")
	public static function optionalDurationValueMicroseconds():haxe.Int64;
	@:hlNative("xavi", "encoded_video_chunk_byte_length")
	public static function byteLength(self:Int):haxe.Int64;
	@:hlNative("xavi", "encoded_video_chunk_copy_to")
	public static function copyTo(self:Int, destination:haxe.io.Bytes):Void;
	@:hlNative("xavi", "encoded_video_chunk_close")
	public static function close(self:Int):Void;
}
