// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract EncodedVideoChunkInit(hl.Abstract<"xavi_EncodedVideoChunkInit">) {
	public inline function new(type:EncodedChunkType, timestamp:haxe.Int64, data:haxe.io.Bytes) this = EncodedVideoChunkInitNative.create(type, timestamp, data);
	public inline function duration(value:haxe.Int64):Void EncodedVideoChunkInitNative.duration(this, value);
}

private extern class EncodedVideoChunkInitNative {
	@:hlNative("xavi", "encoded_video_chunk_init_new")
	public static function create(type:EncodedChunkType, timestamp:haxe.Int64, data:haxe.io.Bytes):hl.Abstract<"xavi_EncodedVideoChunkInit">;
	@:hlNative("xavi", "encoded_video_chunk_init_duration")
	public static function duration(self:hl.Abstract<"xavi_EncodedVideoChunkInit">, value:haxe.Int64):Void;
}
