// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract MediaMuxer(Int) from Int to Int {
	public static inline function audio(path:String, audio:CodecConfiguration, origin:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer return MediaMuxerNative.audio(path, audio, origin, maxItems, maxBytes);
	public static inline function video(path:String, video:CodecConfiguration, origin:haxe.Int64, defaultDuration:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer return MediaMuxerNative.video(path, video, origin, defaultDuration, maxItems, maxBytes);
	public static inline function audioVideo(path:String, audio:CodecConfiguration, video:CodecConfiguration, origin:haxe.Int64, defaultDuration:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer return MediaMuxerNative.audioVideo(path, audio, video, origin, defaultDuration, maxItems, maxBytes);
	public inline function finish():Void MediaMuxerNative.finish(this);
	public inline function finished():Bool return MediaMuxerNative.finished(this);
	public inline function close():Void MediaMuxerNative.close(this);
	public inline function writeAudioChunk(value:EncodedAudioChunk):Bool return MediaMuxerNative.writeAudioChunk(this, value);
	public inline function endAudioTrack():Void MediaMuxerNative.endAudioTrack(this);
	public inline function writeVideoChunk(value:EncodedVideoChunk):Bool return MediaMuxerNative.writeVideoChunk(this, value);
	public inline function endVideoTrack():Void MediaMuxerNative.endVideoTrack(this);
}

private extern class MediaMuxerNative {
	@:hlNative("xavi", "media_muxer_audio")
	public static function audio(path:String, audio:CodecConfiguration, origin:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer;
	@:hlNative("xavi", "media_muxer_video")
	public static function video(path:String, video:CodecConfiguration, origin:haxe.Int64, defaultDuration:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer;
	@:hlNative("xavi", "media_muxer_audio_video")
	public static function audioVideo(path:String, audio:CodecConfiguration, video:CodecConfiguration, origin:haxe.Int64, defaultDuration:haxe.Int64, maxItems:Int, maxBytes:haxe.Int64):MediaMuxer;
	@:hlNative("xavi", "media_muxer_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "media_muxer_finished")
	public static function finished(self:Int):Bool;
	@:hlNative("xavi", "media_muxer_close")
	public static function close(self:Int):Void;
	@:hlNative("xavi", "media_muxer_write_audio_chunk")
	public static function writeAudioChunk(self:Int, value:EncodedAudioChunk):Bool;
	@:hlNative("xavi", "media_muxer_end_audio_track")
	public static function endAudioTrack(self:Int):Void;
	@:hlNative("xavi", "media_muxer_write_video_chunk")
	public static function writeVideoChunk(self:Int, value:EncodedVideoChunk):Bool;
	@:hlNative("xavi", "media_muxer_end_video_track")
	public static function endVideoTrack(self:Int):Void;
}
