// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract MediaDemuxer(Int) from Int to Int {
	public static inline function open(path:String, maxItems:Int, maxBytes:haxe.Int64):MediaDemuxer return MediaDemuxerNative.open(path, maxItems, maxBytes);
	public inline function hasAudio():Bool return MediaDemuxerNative.hasAudio(this);
	public inline function hasVideo():Bool return MediaDemuxerNative.hasVideo(this);
	public inline function duration():Float return MediaDemuxerNative.duration(this);
	public inline function close():Void MediaDemuxerNative.close(this);
	public inline function getAudioConfiguration():CodecConfiguration return MediaDemuxerNative.getAudioConfiguration(this);
	public inline function audioStatus():StreamReadStatus return MediaDemuxerNative.audioStatus(this);
	public inline function readAudioChunk():EncodedAudioChunk return MediaDemuxerNative.readAudioChunk(this);
	public inline function getVideoConfiguration():CodecConfiguration return MediaDemuxerNative.getVideoConfiguration(this);
	public inline function videoStatus():StreamReadStatus return MediaDemuxerNative.videoStatus(this);
	public inline function readVideoChunk():EncodedVideoChunk return MediaDemuxerNative.readVideoChunk(this);
}

private extern class MediaDemuxerNative {
	@:hlNative("xavi", "media_demuxer_open")
	public static function open(path:String, maxItems:Int, maxBytes:haxe.Int64):MediaDemuxer;
	@:hlNative("xavi", "media_demuxer_has_audio")
	public static function hasAudio(self:Int):Bool;
	@:hlNative("xavi", "media_demuxer_has_video")
	public static function hasVideo(self:Int):Bool;
	@:hlNative("xavi", "media_demuxer_duration")
	public static function duration(self:Int):Float;
	@:hlNative("xavi", "media_demuxer_close")
	public static function close(self:Int):Void;
	@:hlNative("xavi", "media_demuxer_get_audio_configuration")
	public static function getAudioConfiguration(self:Int):CodecConfiguration;
	@:hlNative("xavi", "media_demuxer_audio_status")
	public static function audioStatus(self:Int):StreamReadStatus;
	@:hlNative("xavi", "media_demuxer_read_audio_chunk")
	public static function readAudioChunk(self:Int):EncodedAudioChunk;
	@:hlNative("xavi", "media_demuxer_get_video_configuration")
	public static function getVideoConfiguration(self:Int):CodecConfiguration;
	@:hlNative("xavi", "media_demuxer_video_status")
	public static function videoStatus(self:Int):StreamReadStatus;
	@:hlNative("xavi", "media_demuxer_read_video_chunk")
	public static function readVideoChunk(self:Int):EncodedVideoChunk;
}
