// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract MediaPayloadKind(Int) from Int to Int {
	var Audio = 0;
	var Video = 1;
	var AudioChunk = 2;
	var VideoChunk = 3;
	var Bytes = 4;
}
