// Generated by xidl-bindgen. Do not edit by hand.
package media;

/**
 * A native file player with audio output and one polled video frame.
 * Drive on the main event-loop thread. Close each frame after uploading it.
 */
abstract MediaPlayer(Int) from Int to Int {
	public static inline function open(path:String):MediaPlayer return MediaPlayerNative.open(path);
	public inline function state():PlaybackState return MediaPlayerNative.state(this);
	public inline function position():Float return MediaPlayerNative.position(this);
	public inline function duration():Float return MediaPlayerNative.duration(this);
	public inline function volume():Float return MediaPlayerNative.volume(this);
	public inline function play():Void MediaPlayerNative.play(this);
	public inline function pause():Void MediaPlayerNative.pause(this);
	public inline function seek(seconds:Float):Void MediaPlayerNative.seek(this, seconds);
	public inline function setVolume(volume:Float):Void MediaPlayerNative.setVolume(this, volume);
	public inline function pollFrame():Bool return MediaPlayerNative.pollFrame(this);
	public inline function takeFrame():VideoFrame return MediaPlayerNative.takeFrame(this);
	public inline function close():Void MediaPlayerNative.close(this);
}

private extern class MediaPlayerNative {
	@:hlNative("xavi", "media_player_open")
	public static function open(path:String):MediaPlayer;
	@:hlNative("xavi", "media_player_state")
	public static function state(self:Int):PlaybackState;
	@:hlNative("xavi", "media_player_position")
	public static function position(self:Int):Float;
	@:hlNative("xavi", "media_player_duration")
	public static function duration(self:Int):Float;
	@:hlNative("xavi", "media_player_volume")
	public static function volume(self:Int):Float;
	@:hlNative("xavi", "media_player_play")
	public static function play(self:Int):Void;
	@:hlNative("xavi", "media_player_pause")
	public static function pause(self:Int):Void;
	@:hlNative("xavi", "media_player_seek")
	public static function seek(self:Int, seconds:Float):Void;
	@:hlNative("xavi", "media_player_set_volume")
	public static function setVolume(self:Int, volume:Float):Void;
	@:hlNative("xavi", "media_player_poll_frame")
	public static function pollFrame(self:Int):Bool;
	@:hlNative("xavi", "media_player_take_frame")
	public static function takeFrame(self:Int):VideoFrame;
	@:hlNative("xavi", "media_player_close")
	public static function close(self:Int):Void;
}
