// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract MediaQueue(Int) from Int to Int {
	public static inline function create(kind:MediaPayloadKind, maxItems:Int, maxBytes:haxe.Int64):MediaQueue return MediaQueueNative.create(kind, maxItems, maxBytes);
	public inline function poll():StreamReadStatus return MediaQueueNative.poll(this);
	public inline function finish():Void MediaQueueNative.finish(this);
	public inline function close():Void MediaQueueNative.close(this);
	public inline function writeAudio(value:AudioData):Bool return MediaQueueNative.writeAudio(this, value);
	public inline function readAudio():AudioData return MediaQueueNative.readAudio(this);
	public inline function writeVideo(value:VideoFrame):Bool return MediaQueueNative.writeVideo(this, value);
	public inline function readVideo():VideoFrame return MediaQueueNative.readVideo(this);
	public inline function writeAudioChunk(value:EncodedAudioChunk):Bool return MediaQueueNative.writeAudioChunk(this, value);
	public inline function readAudioChunk():EncodedAudioChunk return MediaQueueNative.readAudioChunk(this);
	public inline function writeVideoChunk(value:EncodedVideoChunk):Bool return MediaQueueNative.writeVideoChunk(this, value);
	public inline function readVideoChunk():EncodedVideoChunk return MediaQueueNative.readVideoChunk(this);
	public inline function writeBytes(value:haxe.io.Bytes):Bool return MediaQueueNative.writeBytes(this, value);
	public inline function byteLength():haxe.Int64 return MediaQueueNative.byteLength(this);
	public inline function readBytes(destination:haxe.io.Bytes):haxe.Int64 return MediaQueueNative.readBytes(this, destination);
}

private extern class MediaQueueNative {
	@:hlNative("xavi", "media_queue_create")
	public static function create(kind:MediaPayloadKind, maxItems:Int, maxBytes:haxe.Int64):MediaQueue;
	@:hlNative("xavi", "media_queue_poll")
	public static function poll(self:Int):StreamReadStatus;
	@:hlNative("xavi", "media_queue_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "media_queue_close")
	public static function close(self:Int):Void;
	@:hlNative("xavi", "media_queue_write_audio")
	public static function writeAudio(self:Int, value:AudioData):Bool;
	@:hlNative("xavi", "media_queue_read_audio")
	public static function readAudio(self:Int):AudioData;
	@:hlNative("xavi", "media_queue_write_video")
	public static function writeVideo(self:Int, value:VideoFrame):Bool;
	@:hlNative("xavi", "media_queue_read_video")
	public static function readVideo(self:Int):VideoFrame;
	@:hlNative("xavi", "media_queue_write_audio_chunk")
	public static function writeAudioChunk(self:Int, value:EncodedAudioChunk):Bool;
	@:hlNative("xavi", "media_queue_read_audio_chunk")
	public static function readAudioChunk(self:Int):EncodedAudioChunk;
	@:hlNative("xavi", "media_queue_write_video_chunk")
	public static function writeVideoChunk(self:Int, value:EncodedVideoChunk):Bool;
	@:hlNative("xavi", "media_queue_read_video_chunk")
	public static function readVideoChunk(self:Int):EncodedVideoChunk;
	@:hlNative("xavi", "media_queue_write_bytes")
	public static function writeBytes(self:Int, value:haxe.io.Bytes):Bool;
	@:hlNative("xavi", "media_queue_byte_length")
	public static function byteLength(self:Int):haxe.Int64;
	@:hlNative("xavi", "media_queue_read_bytes")
	public static function readBytes(self:Int, destination:haxe.io.Bytes):haxe.Int64;
}
