// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract PlaneLayout(hl.Abstract<"xavi_PlaneLayout">) {
	public inline function new(offset:haxe.Int64, stride:haxe.Int64) this = PlaneLayoutNative.create(offset, stride);
}

private extern class PlaneLayoutNative {
	@:hlNative("xavi", "plane_layout_new")
	public static function create(offset:haxe.Int64, stride:haxe.Int64):hl.Abstract<"xavi_PlaneLayout">;
}
