// Generated by xidl-bindgen. Do not edit by hand.
package media;

/** Destination layouts, in pixel-format plane order. Close after reading. */
abstract PlaneLayouts(Int) from Int to Int {
	public inline function count():Int return PlaneLayoutsNative.count(this);
	public inline function offset(index:Int):haxe.Int64 return PlaneLayoutsNative.offset(this, index);
	public inline function stride(index:Int):haxe.Int64 return PlaneLayoutsNative.stride(this, index);
	public inline function close():Void PlaneLayoutsNative.close(this);
}

private extern class PlaneLayoutsNative {
	@:hlNative("xavi", "plane_layouts_count")
	public static function count(self:Int):Int;
	@:hlNative("xavi", "plane_layouts_offset")
	public static function offset(self:Int, index:Int):haxe.Int64;
	@:hlNative("xavi", "plane_layouts_stride")
	public static function stride(self:Int, index:Int):haxe.Int64;
	@:hlNative("xavi", "plane_layouts_close")
	public static function close(self:Int):Void;
}
