// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract PlaybackState(Int) from Int to Int {
	var Opening = 0;
	var Paused = 1;
	var Playing = 2;
	var Buffering = 3;
	var Ended = 4;
}
