// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoFrameCopyToOptions(hl.Abstract<"xavi_VideoFrameCopyToOptions">) {
	public inline function new() this = VideoFrameCopyToOptionsNative.create();
	public inline function rect(value:DOMRectInit):Void VideoFrameCopyToOptionsNative.rect(this, value);
	public inline function addLayout(value:PlaneLayout):Void VideoFrameCopyToOptionsNative.addLayout(this, value);
	public inline function format(value:VideoPixelFormat):Void VideoFrameCopyToOptionsNative.format(this, value);
}

private extern class VideoFrameCopyToOptionsNative {
	@:hlNative("xavi", "video_frame_copy_to_options_new")
	public static function create():hl.Abstract<"xavi_VideoFrameCopyToOptions">;
	@:hlNative("xavi", "video_frame_copy_to_options_rect")
	public static function rect(self:hl.Abstract<"xavi_VideoFrameCopyToOptions">, value:DOMRectInit):Void;
	@:hlNative("xavi", "video_frame_copy_to_options_add_layout")
	public static function addLayout(self:hl.Abstract<"xavi_VideoFrameCopyToOptions">, value:PlaneLayout):Void;
	@:hlNative("xavi", "video_frame_copy_to_options_format")
	public static function format(self:hl.Abstract<"xavi_VideoFrameCopyToOptions">, value:VideoPixelFormat):Void;
}
