// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoFrameBufferInit(hl.Abstract<"xavi_VideoFrameBufferInit">) {
	public inline function new(format:VideoPixelFormat, codedWidth:haxe.Int64, codedHeight:haxe.Int64, timestamp:haxe.Int64) this = VideoFrameBufferInitNative.create(format, codedWidth, codedHeight, timestamp);
	public inline function duration(value:haxe.Int64):Void VideoFrameBufferInitNative.duration(this, value);
	public inline function addLayout(value:PlaneLayout):Void VideoFrameBufferInitNative.addLayout(this, value);
	public inline function visibleRect(value:DOMRectInit):Void VideoFrameBufferInitNative.visibleRect(this, value);
	public inline function displayWidth(value:haxe.Int64):Void VideoFrameBufferInitNative.displayWidth(this, value);
	public inline function displayHeight(value:haxe.Int64):Void VideoFrameBufferInitNative.displayHeight(this, value);
	public inline function colorSpace(value:VideoColorSpaceInit):Void VideoFrameBufferInitNative.colorSpace(this, value);
}

private extern class VideoFrameBufferInitNative {
	@:hlNative("xavi", "video_frame_buffer_init_new")
	public static function create(format:VideoPixelFormat, codedWidth:haxe.Int64, codedHeight:haxe.Int64, timestamp:haxe.Int64):hl.Abstract<"xavi_VideoFrameBufferInit">;
	@:hlNative("xavi", "video_frame_buffer_init_duration")
	public static function duration(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:haxe.Int64):Void;
	@:hlNative("xavi", "video_frame_buffer_init_add_layout")
	public static function addLayout(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:PlaneLayout):Void;
	@:hlNative("xavi", "video_frame_buffer_init_visible_rect")
	public static function visibleRect(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:DOMRectInit):Void;
	@:hlNative("xavi", "video_frame_buffer_init_display_width")
	public static function displayWidth(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:haxe.Int64):Void;
	@:hlNative("xavi", "video_frame_buffer_init_display_height")
	public static function displayHeight(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:haxe.Int64):Void;
	@:hlNative("xavi", "video_frame_buffer_init_color_space")
	public static function colorSpace(self:hl.Abstract<"xavi_VideoFrameBufferInit">, value:VideoColorSpaceInit):Void;
}
