// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract VideoTransferCharacteristics(Int) from Int to Int {
	var Bt709 = 0;
	var Smpte170m = 1;
	var Iec6196621 = 2;
	var Linear = 3;
	var Pq = 4;
	var Hlg = 5;
}
