// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoColorSpaceInit(hl.Abstract<"xavi_VideoColorSpaceInit">) {
	public inline function new() this = VideoColorSpaceInitNative.create();
	public inline function primaries(value:VideoColorPrimaries):Void VideoColorSpaceInitNative.primaries(this, value);
	public inline function transfer(value:VideoTransferCharacteristics):Void VideoColorSpaceInitNative.transfer(this, value);
	public inline function matrix(value:VideoMatrixCoefficients):Void VideoColorSpaceInitNative.matrix(this, value);
	public inline function fullRange(value:Bool):Void VideoColorSpaceInitNative.fullRange(this, value);
}

private extern class VideoColorSpaceInitNative {
	@:hlNative("xavi", "video_color_space_init_new")
	public static function create():hl.Abstract<"xavi_VideoColorSpaceInit">;
	@:hlNative("xavi", "video_color_space_init_primaries")
	public static function primaries(self:hl.Abstract<"xavi_VideoColorSpaceInit">, value:VideoColorPrimaries):Void;
	@:hlNative("xavi", "video_color_space_init_transfer")
	public static function transfer(self:hl.Abstract<"xavi_VideoColorSpaceInit">, value:VideoTransferCharacteristics):Void;
	@:hlNative("xavi", "video_color_space_init_matrix")
	public static function matrix(self:hl.Abstract<"xavi_VideoColorSpaceInit">, value:VideoMatrixCoefficients):Void;
	@:hlNative("xavi", "video_color_space_init_full_range")
	public static function fullRange(self:hl.Abstract<"xavi_VideoColorSpaceInit">, value:Bool):Void;
}
