// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract VideoMatrixCoefficients(Int) from Int to Int {
	var Rgb = 0;
	var Bt709 = 1;
	var Bt470bg = 2;
	var Smpte170m = 3;
	var Bt2020Ncl = 4;
}
