// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract VideoPixelFormat(Int) from Int to Int {
	var I420 = 0;
	var I420A = 1;
	var I422 = 2;
	var I444 = 3;
	var NV12 = 4;
	var RGBA = 5;
	var RGBX = 6;
	var BGRA = 7;
	var BGRX = 8;
}
