// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoDecoder(Int) from Int to Int {
	public static inline function create(maxItems:Int, maxBytes:haxe.Int64, configuration:CodecConfiguration):VideoDecoder return VideoDecoderNative.create(maxItems, maxBytes, configuration);
	public inline function tryDecode(value:EncodedVideoChunk):Bool return VideoDecoderNative.tryDecode(this, value);
	public inline function poll():StreamReadStatus return VideoDecoderNative.poll(this);
	public inline function read():VideoFrame return VideoDecoderNative.read(this);
	public inline function finish():Void VideoDecoderNative.finish(this);
	public inline function close():Void VideoDecoderNative.close(this);
}

private extern class VideoDecoderNative {
	@:hlNative("xavi", "video_decoder_create")
	public static function create(maxItems:Int, maxBytes:haxe.Int64, configuration:CodecConfiguration):VideoDecoder;
	@:hlNative("xavi", "video_decoder_try_decode")
	public static function tryDecode(self:Int, value:EncodedVideoChunk):Bool;
	@:hlNative("xavi", "video_decoder_poll")
	public static function poll(self:Int):StreamReadStatus;
	@:hlNative("xavi", "video_decoder_read")
	public static function read(self:Int):VideoFrame;
	@:hlNative("xavi", "video_decoder_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "video_decoder_close")
	public static function close(self:Int):Void;
}
