// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoEncoder(Int) from Int to Int {
	public static inline function create(codec:String, width:haxe.Int64, height:haxe.Int64, bitrate:haxe.Int64, framerate:Float, maxItems:Int, maxBytes:haxe.Int64):VideoEncoder return VideoEncoderNative.create(codec, width, height, bitrate, framerate, maxItems, maxBytes);
	public inline function tryEncode(value:VideoFrame):Bool return VideoEncoderNative.tryEncode(this, value);
	public inline function poll():StreamReadStatus return VideoEncoderNative.poll(this);
	public inline function read():EncodedVideoChunk return VideoEncoderNative.read(this);
	public inline function finish():Void VideoEncoderNative.finish(this);
	public inline function close():Void VideoEncoderNative.close(this);
	public inline function getConfiguration():CodecConfiguration return VideoEncoderNative.getConfiguration(this);
}

private extern class VideoEncoderNative {
	@:hlNative("xavi", "video_encoder_create")
	public static function create(codec:String, width:haxe.Int64, height:haxe.Int64, bitrate:haxe.Int64, framerate:Float, maxItems:Int, maxBytes:haxe.Int64):VideoEncoder;
	@:hlNative("xavi", "video_encoder_try_encode")
	public static function tryEncode(self:Int, value:VideoFrame):Bool;
	@:hlNative("xavi", "video_encoder_poll")
	public static function poll(self:Int):StreamReadStatus;
	@:hlNative("xavi", "video_encoder_read")
	public static function read(self:Int):EncodedVideoChunk;
	@:hlNative("xavi", "video_encoder_finish")
	public static function finish(self:Int):Void;
	@:hlNative("xavi", "video_encoder_close")
	public static function close(self:Int):Void;
	@:hlNative("xavi", "video_encoder_get_configuration")
	public static function getConfiguration(self:Int):CodecConfiguration;
}
