// Generated by xidl-bindgen. Do not edit by hand.
package media;

abstract VideoFrame(Int) from Int to Int {
	public static inline function create(data:haxe.io.Bytes, init:VideoFrameBufferInit):VideoFrame return VideoFrameNative.create(data, init);
	public inline function format():VideoPixelFormat return VideoFrameNative.format(this);
	public inline function codedWidth():haxe.Int64 return VideoFrameNative.codedWidth(this);
	public inline function codedHeight():haxe.Int64 return VideoFrameNative.codedHeight(this);
	public inline function displayWidth():haxe.Int64 return VideoFrameNative.displayWidth(this);
	public inline function displayHeight():haxe.Int64 return VideoFrameNative.displayHeight(this);
	static inline function readPixelRect(index:Int):PixelRect {
		return PixelRect.Value(VideoFrameNative.pixelRectValueX(), VideoFrameNative.pixelRectValueY(), VideoFrameNative.pixelRectValueWidth(), VideoFrameNative.pixelRectValueHeight());
	}
	public inline function visibleRect():PixelRect {
		return readPixelRect(VideoFrameNative.visibleRectVariant(this));
	}
	static inline function colorSpaceValuePrimaries():OptionalPrimaries {
		return switch (VideoFrameNative.colorSpaceValuePrimariesVariant()) {
			case 1: OptionalPrimaries.Value(VideoFrameNative.colorSpaceValuePrimariesValueValue());
			default: OptionalPrimaries.Unknown;
		};
	}
	static inline function colorSpaceValueTransfer():OptionalTransfer {
		return switch (VideoFrameNative.colorSpaceValueTransferVariant()) {
			case 1: OptionalTransfer.Value(VideoFrameNative.colorSpaceValueTransferValueValue());
			default: OptionalTransfer.Unknown;
		};
	}
	static inline function colorSpaceValueMatrix():OptionalMatrix {
		return switch (VideoFrameNative.colorSpaceValueMatrixVariant()) {
			case 1: OptionalMatrix.Value(VideoFrameNative.colorSpaceValueMatrixValueValue());
			default: OptionalMatrix.Unknown;
		};
	}
	static inline function colorSpaceValueFullRange():OptionalBool {
		return switch (VideoFrameNative.colorSpaceValueFullRangeVariant()) {
			case 1: OptionalBool.Value(VideoFrameNative.colorSpaceValueFullRangeValueValue());
			default: OptionalBool.Unknown;
		};
	}
	static inline function readColorSpace(index:Int):ColorSpace {
		return ColorSpace.Value(colorSpaceValuePrimaries(), colorSpaceValueTransfer(), colorSpaceValueMatrix(), colorSpaceValueFullRange());
	}
	public inline function colorSpace():ColorSpace {
		return readColorSpace(VideoFrameNative.colorSpaceVariant(this));
	}
	public inline function timestamp():haxe.Int64 return VideoFrameNative.timestamp(this);
	static inline function readOptionalDuration(index:Int):OptionalDuration {
		return switch (index) {
			case 1: OptionalDuration.Value(VideoFrameNative.optionalDurationValueMicroseconds());
			default: OptionalDuration.Unknown;
		};
	}
	public inline function duration():OptionalDuration {
		return readOptionalDuration(VideoFrameNative.durationVariant(this));
	}
	public inline function allocationSize(options:VideoFrameCopyToOptions):haxe.Int64 return VideoFrameNative.allocationSize(this, options);
	public inline function copyTo(destination:haxe.io.Bytes, options:VideoFrameCopyToOptions):ash.Future<PlaneLayouts> return VideoFrameNative.copyTo(this, destination, options);
	public inline function clone():VideoFrame return VideoFrameNative.clone(this);
	public inline function close():Void VideoFrameNative.close(this);
}

private extern class VideoFrameNative {
	@:hlNative("xavi", "video_frame_create")
	public static function create(data:haxe.io.Bytes, init:VideoFrameBufferInit):VideoFrame;
	@:hlNative("xavi", "video_frame_format")
	public static function format(self:Int):VideoPixelFormat;
	@:hlNative("xavi", "video_frame_coded_width")
	public static function codedWidth(self:Int):haxe.Int64;
	@:hlNative("xavi", "video_frame_coded_height")
	public static function codedHeight(self:Int):haxe.Int64;
	@:hlNative("xavi", "video_frame_display_width")
	public static function displayWidth(self:Int):haxe.Int64;
	@:hlNative("xavi", "video_frame_display_height")
	public static function displayHeight(self:Int):haxe.Int64;
	@:hlNative("xavi", "video_frame_visible_rect_variant")
	public static function visibleRectVariant(self:Int):Int;
	@:hlNative("xavi", "video_frame_pixel_rect_value_x")
	public static function pixelRectValueX():haxe.Int64;
	@:hlNative("xavi", "video_frame_pixel_rect_value_y")
	public static function pixelRectValueY():haxe.Int64;
	@:hlNative("xavi", "video_frame_pixel_rect_value_width")
	public static function pixelRectValueWidth():haxe.Int64;
	@:hlNative("xavi", "video_frame_pixel_rect_value_height")
	public static function pixelRectValueHeight():haxe.Int64;
	@:hlNative("xavi", "video_frame_color_space_variant")
	public static function colorSpaceVariant(self:Int):Int;
	@:hlNative("xavi", "video_frame_color_space_value_primaries_variant")
	public static function colorSpaceValuePrimariesVariant():Int;
	@:hlNative("xavi", "video_frame_color_space_value_primaries_value_value")
	public static function colorSpaceValuePrimariesValueValue():VideoColorPrimaries;
	@:hlNative("xavi", "video_frame_color_space_value_transfer_variant")
	public static function colorSpaceValueTransferVariant():Int;
	@:hlNative("xavi", "video_frame_color_space_value_transfer_value_value")
	public static function colorSpaceValueTransferValueValue():VideoTransferCharacteristics;
	@:hlNative("xavi", "video_frame_color_space_value_matrix_variant")
	public static function colorSpaceValueMatrixVariant():Int;
	@:hlNative("xavi", "video_frame_color_space_value_matrix_value_value")
	public static function colorSpaceValueMatrixValueValue():VideoMatrixCoefficients;
	@:hlNative("xavi", "video_frame_color_space_value_full_range_variant")
	public static function colorSpaceValueFullRangeVariant():Int;
	@:hlNative("xavi", "video_frame_color_space_value_full_range_value_value")
	public static function colorSpaceValueFullRangeValueValue():Bool;
	@:hlNative("xavi", "video_frame_timestamp")
	public static function timestamp(self:Int):haxe.Int64;
	@:hlNative("xavi", "video_frame_duration_variant")
	public static function durationVariant(self:Int):Int;
	@:hlNative("xavi", "video_frame_optional_duration_value_microseconds")
	public static function optionalDurationValueMicroseconds():haxe.Int64;
	@:hlNative("xavi", "video_frame_allocation_size")
	public static function allocationSize(self:Int, options:VideoFrameCopyToOptions):haxe.Int64;
	@:hlNative("xavi", "video_frame_copy_to")
	public static function copyTo(self:Int, destination:haxe.io.Bytes, options:VideoFrameCopyToOptions):ash.Future<PlaneLayouts>;
	@:hlNative("xavi", "video_frame_clone")
	public static function clone(self:Int):VideoFrame;
	@:hlNative("xavi", "video_frame_close")
	public static function close(self:Int):Void;
}
