// Generated by xidl-bindgen. Do not edit by hand.
package media;

enum abstract VideoColorPrimaries(Int) from Int to Int {
	var Bt709 = 0;
	var Bt470bg = 1;
	var Smpte170m = 2;
	var Bt2020 = 3;
	var Smpte432 = 4;
}
